// Generated by CoffeeScript 1.9.2
var app, bodyParser, express, mongoose, mongooseURL, port, server;

mongoose = require('mongoose');

express = require('express');

server = require('http').createServer(app);

bodyParser = require('body-parser');

mongooseURL = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || 'mongodb://localhost/parallellocalypse';

mongoose.connect(mongooseURL, function(err) {
  if (err) {
    throw err;
  }
  return console.log("Connected to MongoDB");
});

port = process.env.PORT || 8080;

app = express();

app.use(bodyParser());

app.use(express["static"](__dirname + '/public'));

app.use(require('./controllers/devices_controller'));

app.listen(port, function() {
  return console.log("Server listening on port " + port);
});
