<!DOCTYPE html>
<html>
	<head>
		<title>parallellocalypse</title>

		<link rel="shortcut icon" href="/img/favicon.png">

		<link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/bower_components/world-flags-sprite/stylesheets/flags16.css">

		<link rel="stylesheet" type="text/css" href="/css/main.css">
	</head>
	<body>
		{% block content %}{% endblock %}

		<script type="text/javascript" src="/bower_components/requirejs/require.js"></script>
		<script type="text/javascript" src="/js/main.js"></script>

	</body>
</html>
